import React from "react";
import type { Metadata } from "next";
import { Inter } from 'next/font/google';

import "@/style/globals.css";
import { cn } from "@/lib/utils";
import AppProvider from "@/provider";
import { Toaster } from "@ui/sonner";

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className='h-full antialiased'
      suppressHydrationWarning
    >
      <body className={cn(inter.className, "min-h-full flex flex-col")}>
        <AppProvider>
          {children}
          <Toaster position="top-right" />
        </AppProvider>
      </body>
    </html>
  );
}
